### ISSUE TITLE
Guild masters are not able to toggle the status of their guild.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#36]
Guilds version 1.7.7-RELEASE

Typing ```/guild status public``` or ```/guild status private``` as the guild leader outputs 'Your role is not high enough to do that!'.

The permission is inherited in the plugin.yml.
```
  guilds.group.member:
    description: All commands for the Guilds plugin
    children:
      guilds.command.accept: true
      guilds.command.boot: true
      guilds.command.cancel: true
      guilds.command.chat: true
      guilds.command.confirm: true
      guilds.command.create: true
      guilds.command.delete: true
      guilds.command.demote: true
      guilds.command.help: true
      guilds.command.info: true
      guilds.command.invite: true
      guilds.command.leave: true
      guilds.command.prefix: true
      guilds.command.promote: true
      guilds.command.role: true
      guilds.command.version: true
      guilds.command.list: true
      guilds.command.bugreport: true
      guilds.command.home: true
      guilds.command.sethome: true
      guilds.command.inspect: true
      guilds.command.status: true
      guilds.command.vault: true
      guilds.command.ally: true
      guilds.command.transfer: true
      guilds.command.buff: true
      guilds.command.decline: true
      guilds.command.check: true
    default: true
```

The default config allows guild masters to toggle-guild by default, but this does not function whatsoever.
```
roles:
  0:
    name: "GuildMaster"
    permissions:
      chat: false
      ally-chat: false
      invite: true
      kick: true
      promote: true
      demote: true
      add-ally: true
      remove-ally: true
      change-prefix: true
      change-home: true
      change-master: true
      remove-guild: true
      toggle-guild: true
      open-vault: false
      transfer-guild: true
      activate-buff: false

  1:
    name: "Officer"
    permissions:
      chat: false
      ally-chat: false
      invite: true
      kick: true
      promote: true
      demote: true
      add-ally: true
      remove-ally: true
      change-prefix: false
      change-home: true
      change-master: false
      remove-guild: false
      toggle-guild: false
      open-vault: false
      transfer-guild: false
      activate-buff: false

  2:
    name: "Veteran"
    permissions:
      chat: false
      ally-chat: false
      invite: true
      kick: false
      promote: false
      demote: false
      add-ally: false
      remove-ally: false
      change-prefix: false
      change-master: false
      remove-guild: false
      toggle-guild: false
      open-vault: false
      transfer-guild: false
      activate-buff: false

  3:
    name: "Member"
    permissions:
      chat: false
      ally-chat: false
      invite: false
      kick: false
      promote: false
      demote: false
      add-ally: false
      remove-ally: false
      change-prefix: false
      change-master: false
      remove-guild: false
      toggle-guild: false
      open-vault: false
      transfer-guild: false
      activate-buff: false
```
