### ISSUE TITLE
Reloading config does not reinitialize changed role settings.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#42]
Reloading via ```/guild reload``` does not reinitialize changed role permission settings. So you can't enable or disable settings on the fly, i.e. if you wanted to change access to vault from allow to deny.

```
roles:
  0:
    name: "GuildMaster"
    permissions:
      open-vault: false
```
