### ISSUE TITLE
Unable to toggle status of guild.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#75]
Guilds 1.9.4 dev 256.

@darbyjack Guild owners are not able to toggle the status of their guild with ```/guild status public```. It returns ```[Guilds] Your role is not high enough to do that!``` when they type the command.

They are the GuildMaster / creator of their guild.

```
roles:
  0:
    name: "GuildMaster"
    permissions:
      activate-buff: false
      add-ally: true
      ally-chat: false
      change-home: true
      change-prefix: true
      chat: false
      demote: true
      deposit-money: false
      invite: true
      kick: true
      open-vault: false
      promote: true
      remove-ally: true
      remove-guild: true
      toggle-guild: true
      transfer-guild: true
      upgrade-guild: true
      withdraw-money: false
      claim-land: false
      unclaim-land: false

  1:
    name: "Officer"
    permissions:
      activate-buff: false
      add-ally: true
      ally-chat: false
      change-home: true
      change-prefix: false
      chat: false
      demote: true
      deposit-money: false
      invite: true
      kick: true
      open-vault: false
      promote: true
      remove-ally: true
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: true
      claim-land: false
      unclaim-land: false

  2:
    name: "Veteran"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: false
      change-prefix: false
      chat: false
      demote: false
      deposit-money: false
      invite: true
      kick: false
      open-vault: false
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
  3:
    name: "Member"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: false
      change-prefix: false
      chat: false
      demote: false
      deposit-money: false
      invite: false
      kick: false
      open-vault: false
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
```
