### ISSUE TITLE
[Feature] Icon Customization

### ISSUE THREAD

**Issue by UltraFaceguy** [darbyjack/Guilds-Plugin#83]
It'd be neat if we could completely customize the guild icons, instead of having options to toggle on/off. Something like this in the config.

```
guild-list-icon:
  display-name: '&f{guild-name} is a &7Guild'
  lore:
  - '&fGuild Master: &b{guild-master}'
  - '&2Guild Tier: {guild-tier}'
  - '&dMembers:&f {member-count}'
  - 'dank memes'
  - 'to join a guild, do x y and z!'
```
